### ISSUE TITLE
[gradle appRun] database connection exception

### ISSUE THREAD

**Issue by mrtuborg** [privacybydesign/irma_keyshare_server#14]
Hello,

I was able to setup and configure `irma_keyshare_server`.
I have tested my installation of mysql (see: [gist](https://gist.github.com/mrtuborg/5853b974f68bbfb73fe5f0e81aade22f))
I have tested access to `irma_keyshare` database through jdbc 
- see [java code](https://gist.github.com/mrtuborg/98b575dab74965e8269e7a14f8398850),
- see [result](https://gist.github.com/mrtuborg/d04124fa68151762e0cdde9e1df3637f)

But `irma_keyshare_server`is unable to connect to the same database:
```
1. org.javalite.activejdbc.InitException: Failed to connect to JNDI name: java:comp/env/jdbc/irma_keyshare

```
My [irma_keyshare_server/src/main/resources/database.xml](https://gist.github.com/mrtuborg/0437b0efd2e93546352c825f87a6d7ea) config
The whole stack trace: [gist](https://gist.github.com/mrtuborg/ecdc579ed2914d51d16e4ea55b34c3bd)

**Comment by mrtuborg** [comment]
I have tried 2 setups:
1. Linux machine with irma configured by script from @confiks (https://gist.github.com/confiks/ab7ae1802d2b64dc20659c0addcc5613)
2. OS X machine with mysql 5.7 in docker container (database irma_keyshared was preconfigured by database.sql script from irma_keyshare_server)


 Both setups does not work.

**Comment by mrtuborg** [comment]
Fixed. Will clarify README.md and prepare PR.

**Comment by sietseringers** [comment]
Hi @mrtuborg,

Thanks for your continued interest, and apologies for the late response! I was still looking into your problem, as far as I could tell your configuration seems fine. Great that you managed to solve it, I'm very curious how.
